export interface SearchableSelectOption {
    value: string
    label: string
}

export interface TherapeuticFilterState {
    therapeuticAreas: string[]
    statuses: string[]
    diseaseTypes: string[]
    primaryDrugs: string[]
    trialPhases: string[]
    patientSegments: string[]
    lineOfTherapy: string[]
    countries: string[]
    sponsorsCollaborators: string[]
    sponsorFieldActivity: string[]
    associatedCro: string[]
    trialTags: string[]
    sex: string[]
    healthyVolunteers: string[]
    trialRecordStatus: string[]
    // Additional fields from trial creation form
    otherDrugs: string[]
    regions: string[]
    ageMin: string[]
    ageMax: string[]
    subjectType: string[]
    ecogPerformanceStatus: string[]
    priorTreatments: string[]
    biomarkerRequirements: string[]
    estimatedEnrollment: string[]
    actualEnrollment: string[]
    enrollmentStatus: string[]
    recruitmentPeriod: string[]
    studyCompletionDate: string[]
    primaryCompletionDate: string[]
    populationDescription: string[]
    studySites: string[]
    principalInvestigators: string[]
    siteStatus: string[]
    siteCountries: string[]
    siteRegions: string[]
    siteContactInfo: string[]
    trialResults: string[]
    trialOutcomeContent: string[]
    resultsAvailable: string[]
    endpointsMet: string[]
    adverseEventsReported: string[]
    studyStartDate: string[]
    firstPatientIn: string[]
    lastPatientIn: string[]
    studyEndDate: string[]
    interimAnalysisDates: string[]
    finalAnalysisDate: string[]
    regulatorySubmissionDate: string[]
    purposeOfTrial: string[]
    summary: string[]
    primaryOutcomeMeasures: string[]
    otherOutcomeMeasures: string[]
    studyDesignKeywords: string[]
    studyDesign: string[]
    treatmentRegimen: string[]
    numberOfArms: string[]
    inclusionCriteria: string[]
    exclusionCriteria: string[]
    ageFrom: string[]
    ageTo: string[]
    gender: string[]
    targetNoVolunteers: string[]
    actualEnrolledVolunteers: string[]
    startDateEstimated: string[]
    trialEndDateEstimated: string[]
    trialOutcome: string[]
    adverseEventReported: string[]
    adverseEventType: string[]
    treatmentForAdverseEvents: string[]
    totalSites: string[]
    siteNotes: string[]
    publicationType: string[]
    registryName: string[]
    studyType: string[]
}

// Default empty filter state
export const DEFAULT_THERAPEUTIC_FILTERS: TherapeuticFilterState = {
    therapeuticAreas: [],
    statuses: [],
    diseaseTypes: [],
    primaryDrugs: [],
    trialPhases: [],
    patientSegments: [],
    lineOfTherapy: [],
    countries: [],
    sponsorsCollaborators: [],
    sponsorFieldActivity: [],
    associatedCro: [],
    trialTags: [],
    sex: [],
    healthyVolunteers: [],
    trialRecordStatus: [],
    otherDrugs: [],
    regions: [],
    ageMin: [],
    ageMax: [],
    subjectType: [],
    ecogPerformanceStatus: [],
    priorTreatments: [],
    biomarkerRequirements: [],
    estimatedEnrollment: [],
    actualEnrollment: [],
    enrollmentStatus: [],
    recruitmentPeriod: [],
    studyCompletionDate: [],
    primaryCompletionDate: [],
    populationDescription: [],
    studySites: [],
    principalInvestigators: [],
    siteStatus: [],
    siteCountries: [],
    siteRegions: [],
    siteContactInfo: [],
    trialResults: [],
    trialOutcomeContent: [],
    resultsAvailable: [],
    endpointsMet: [],
    adverseEventsReported: [],
    studyStartDate: [],
    firstPatientIn: [],
    lastPatientIn: [],
    studyEndDate: [],
    interimAnalysisDates: [],
    finalAnalysisDate: [],
    regulatorySubmissionDate: [],
    purposeOfTrial: [],
    summary: [],
    primaryOutcomeMeasures: [],
    otherOutcomeMeasures: [],
    studyDesignKeywords: [],
    studyDesign: [],
    treatmentRegimen: [],
    numberOfArms: [],
    inclusionCriteria: [],
    exclusionCriteria: [],
    ageFrom: [],
    ageTo: [],
    gender: [],
    targetNoVolunteers: [],
    actualEnrolledVolunteers: [],
    startDateEstimated: [],
    trialEndDateEstimated: [],
    trialOutcome: [],
    adverseEventReported: [],
    adverseEventType: [],
    treatmentForAdverseEvents: [],
    totalSites: [],
    siteNotes: [],
    publicationType: [],
    registryName: [],
    studyType: [],
}

export interface TherapeuticSearchCriteria {
    id: string
    field: string
    operator: string
    value: string | string[] // Support both single string and array of strings
    logic: "AND" | "OR"
}
